// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBTqXpRATfNBKdJSTcpD0QqCXJ42MM_qw',
    appId: '1:141170934173:web:placeholder', // TODO: Reemplazar con el App ID real de Web si falla
    messagingSenderId: '141170934173',
    projectId: 'sicopa-verificaciones',
    authDomain: 'sicopa-verificaciones.firebaseapp.com',
    storageBucket: 'sicopa-verificaciones.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBTqXpRATfNBKdJSTcpD0QqCXJ42MM_qw',
    appId: '1:141170934173:android:placeholder', // No tengo el google-services.json
    messagingSenderId: '141170934173',
    projectId: 'sicopa-verificaciones',
    storageBucket: 'sicopa-verificaciones.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBTqXpRATfNBKdJSTcpD0QqCXJ42MM_qw',
    appId: '1:141170934173:ios:6a2d79f53222ae8e956f74',
    messagingSenderId: '141170934173',
    projectId: 'sicopa-verificaciones',
    storageBucket: 'sicopa-verificaciones.firebasestorage.app',
    iosBundleId: 'com.sicopa.inventarios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBTqXpRATfNBKdJSTcpD0QqCXJ42MM_qw',
    appId: '1:141170934173:ios:6a2d79f53222ae8e956f74',
    messagingSenderId: '141170934173',
    projectId: 'sicopa-verificaciones',
    storageBucket: 'sicopa-verificaciones.firebasestorage.app',
    iosBundleId: 'com.sicopa.inventarios',
  );
}
